# Generated by Django 5.0.3 on 2026-05-15 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revlabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_hp', models.IntegerField(help_text='Bonus HP')),
                ('added_weight_kg', models.IntegerField(help_text='Weight added/removed (use negative for weight reduction)')),
                ('image_path', models.CharField(help_text="e.g., 'img/turbo-icon.png'", max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='revlabs.partcategory')),
            ],
        ),
    ]
