# Generated by Django 5.0.3 on 2026-05-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revlabs', '0002_partcategory_carpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='main_category',
            field=models.CharField(choices=[('engine', 'Engine'), ('suspension', 'Suspension'), ('transmission', 'Transmission'), ('chassis', 'Chassis'), ('aerodynamics', 'Aerodynamics'), ('drivetrain', 'Drivetrain'), ('brakes', 'Brakes'), ('tyres', 'Tyres')], default='engine', help_text='The main system this part belongs to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='name',
            field=models.CharField(help_text='Specific part name (e.g., Low-RPM Turbocharger)', max_length=100),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='name',
            field=models.CharField(help_text='Subcategory name (e.g., Turbochargers)', max_length=100, unique=True),
        ),
    ]
