# Generated by Django 6.0.5 on 2026-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revlabs', '0003_partcategory_main_category_alter_carpart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='bg_image_path',
            field=models.CharField(blank=True, help_text="e.g., 'img/monza-bg.jpg'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image_path',
            field=models.CharField(help_text="e.g., 'img/monza-layout.png'", max_length=255),
        ),
    ]
