# Generated by Django 6.0.5 on 2026-06-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revlabs', '0004_track_bg_image_path_alter_track_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_code',
            field=models.IntegerField(blank=True, help_text='GT7 car_code (e.g., 3539 for Porsche 911 GT3 RS)', null=True),
        ),
        migrations.AddField(
            model_name='carpart',
            name='gt7_part_id',
            field=models.CharField(blank=True, help_text='GT7 internal part ID for mapping', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_id',
            field=models.IntegerField(blank=True, help_text='GT7 track_id (e.g., 152 for Interlagos)', null=True),
        ),
        migrations.CreateModel(
            name='TelemetryLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(help_text='Lap number in the original session')),
                ('lap_time_ms', models.IntegerField(blank=True, null=True)),
                ('lap_time_seconds', models.FloatField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('has_mods', models.BooleanField(default=False, help_text='Whether modifications were installed')),
                ('mods_hash', models.CharField(blank=True, help_text='SHA256 hash of installed mod config', max_length=64, null=True)),
                ('avg_speed_kmh', models.FloatField(blank=True, null=True)),
                ('max_speed_kmh', models.FloatField(blank=True, null=True)),
                ('min_speed_kmh', models.FloatField(blank=True, null=True)),
                ('max_rpm', models.FloatField(blank=True, null=True)),
                ('avg_throttle_pct', models.FloatField(blank=True, null=True)),
                ('avg_brake_pct', models.FloatField(blank=True, null=True)),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('original_session_id', models.IntegerField(blank=True, null=True)),
                ('original_lap_id', models.IntegerField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_laps', to='revlabs.car')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_laps', to='revlabs.track')),
            ],
            options={
                'ordering': ['lap_time_ms'],
                'indexes': [models.Index(fields=['car', 'track', 'lap_time_ms'], name='revlabs_tel_car_id_50cf15_idx'), models.Index(fields=['car', 'track', 'is_complete'], name='revlabs_tel_car_id_dd9bad_idx')],
            },
        ),
    ]
