# Generated by Django 6.0.5 on 2026-06-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revlabs', '0005_car_car_code_carpart_gt7_part_id_track_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='gt7_tier',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('club_sports', 'Club Sports'), ('semi_racing', 'Semi-Racing'), ('racing', 'Racing'), ('extreme', 'Extreme'), ('special', 'Special / Roulette')], help_text='GT7 tuning shop tier this part belongs to', max_length=20, null=True),
        ),
    ]
