# Generated by Django 6.0.5 on 2026-06-20 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revlabs', '0006_carpart_gt7_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='is_adjustable',
            field=models.BooleanField(default=False, help_text='Whether this part has user-configurable settings'),
        ),
        migrations.CreateModel(
            name='PartAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_key', models.CharField(help_text="e.g., 'ride_height_front'", max_length=60)),
                ('label', models.CharField(help_text='Display label for the slider', max_length=100)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('step', models.FloatField(default=1.0)),
                ('default_value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', help_text="e.g., 'mm', '%', 'Hz'", max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='revlabs.carpart')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('part', 'param_key')},
            },
        ),
    ]
