# Generated by Django 6.0.5 on 2026-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revlabs', '0007_carpart_is_adjustable_partadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylap',
            name='sector_1_ms',
            field=models.IntegerField(blank=True, help_text='Sector 1 time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='telemetrylap',
            name='sector_2_ms',
            field=models.IntegerField(blank=True, help_text='Sector 2 time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='telemetrylap',
            name='sector_3_ms',
            field=models.IntegerField(blank=True, help_text='Sector 3 time in milliseconds', null=True),
        ),
    ]
